In [1]:
import numpy as np

X = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(X)

[[-11.07181707 -12.80902171   0.27155179 ...   3.48617804  27.9137652
   -2.2560932 ]
 [ 10.70520317   1.26092272  12.56503707 ... -10.16461888  11.23373796
   -0.32602484]
 [  0.29530106   6.51517966 -19.74369865 ...  10.49954212  13.94790108
   -5.41802999]
 ...
 [  2.39770924  19.66639071  -3.84190538 ... -10.33857808  -2.47277062
   -8.52932719]
 [  9.2746734    5.69942628   5.80684423 ...  -9.9185383   11.89953749
   -8.68747759]
 [  8.49947318  -3.86736092  22.02109877 ...  -3.2759812   -5.60067305
   21.83615081]]


In [6]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)

x_norm = ((X - m) / std)

print(x_norm)

[[-1.1842311  -1.37410224 -0.0794666  ...  0.23030974  2.70149389
  -0.33828758]
 [ 0.89097853  0.04024994  1.16374559 ... -1.09193502  1.04898227
  -0.15325057]
 [-0.10101803  0.56842329 -2.10356331 ...  0.90963887  1.31787788
  -0.64142468]
 ...
 [ 0.09932792  1.89042169 -0.49545116 ... -1.10878508 -0.30893905
  -0.93970692]
 [ 0.75465827  0.48642136  0.48030493 ... -1.06809914  1.11494388
  -0.95486891]
 [ 0.68078668 -0.47526021  2.12001558 ... -0.42468716 -0.61882434
   1.97145275]]


In [14]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

sum = np.sum(Z, axis=1)
res = np.nonzero(sum > 10)
print(res)


(array([1, 4, 5]),)


In [19]:
X = np.eye(3)
Y = np.eye(3)
res = np.vstack((X, Y))
print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
